name: halfpipe
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies: 
  dcli_core: ^1.22.5
  dcli_filesystem: ^1.22.5
  path: ^1.8.3
  posix: ^4.1.0

dev_dependencies:
  lint_hard: ^1.0.0
  test: ^1.16.0
