name: halfpipe
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies: 
  async: ^2.11.0
  dcli: ^4.0.1-beta.4
  dcli_common: ^4.0.1-beta.4
  dcli_core: ^4.0.1-beta.4
  file: ^7.0.0
  glob: ^2.1.2
  path: ^1.8.3
  posix: ^6.0.0
  stack_trace: ^1.11.1

dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.16.0
