name: halfpipe
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies: 
  args: ^2.5.0
  async: ^2.11.0
  completer_ex: ^4.0.2
  dcli: ^4.0.0
  dcli_common: ^4.0.0
  dcli_core: ^4.0.0
  file: ^7.0.0
  glob: ^2.1.2
  logging: ^1.2.0
  path: ^1.8.3
  posix: ^6.0.0
  stack_trace: ^1.11.1

dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.16.0
